theme: jekyll-theme-leap-day
title: Game Sale Analysis
description: A CMSC320 Final Project at University of Maryland, College Park. Written by Siyuan "Kevin" Peng, Yuanzhe "Siris" Zheng, Yanlin "Jacky" Liu. Publish Data 12/17/2020.